In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_excel("mtpdata6.xlsx")

In [3]:
data.shape

(196, 3)

In [4]:
data.head()

   Relay Height  Amplitude  Time Period
0           6.0     0.0655       2.5988
1           6.0     0.0830       2.7200
2           6.0     0.0960       2.8004
3           6.0     0.0840       2.8240
4           6.0     0.0625       2.8216

In [5]:
# data['Division'] = data['Time period']/1000

In [6]:
# data.head()

In [7]:
# data.drop(['Time period'], axis = 1, inplace = True)

In [8]:
# data.head()

In [9]:
# data['Time period'] = data['Division']

In [10]:
# data.drop(['Division'], axis = 1, inplace = True)

In [11]:
# data.head()

In [12]:
data.head()

   Relay Height  Amplitude  Time Period
0           6.0     0.0655       2.5988
1           6.0     0.0830       2.7200
2           6.0     0.0960       2.8004
3           6.0     0.0840       2.8240
4           6.0     0.0625       2.8216

In [13]:
H = data['Relay Height'].tolist()
Ti = data['Time Period'].tolist()
A = data['Amplitude'].tolist()

In [14]:
# gain = []
# for i in range(len(data['Amplitude'])):
#     num = random.randint(1,1)
#     gain.append(num)

In [15]:
# gain = []
# for i in range(len(A)):
#     K = (4*H[i])/(3.1415*A[i])
#     gain.append(K)

In [16]:
# gain
# data['Gain'] = gain
# K = data['Gain'].tolist()

In [17]:
Time = []
for i in range(len(A)):
    wcr = (2*3.1415)/(Ti[i])
    a = (4*H[i])/((3.1415)*A[i])
    b = a**2 - 1
    T = ((b**0.5)/wcr).real
    Time.append(T)

In [18]:
Time

[48.24171219785802,
 39.84485927292754,
 35.466771969127535,
 40.87580047126723,
 54.89186839237098,
 43.41788035907825,
 51.560704221991614,
 41.024091321262354,
 41.32278967475873,
 41.03031632281514,
 46.299593187083474,
 58.937492699519,
 61.007118048492735,
 58.0041085093457,
 49.12509965015492,
 52.18172156293777,
 53.44995590725482,
 50.18717482107617,
 54.483998376992965,
 53.58545398294725,
 48.82216933716908,
 56.57058356806519,
 54.393035209329085,
 58.389007179275744,
 65.5602670802078,
 52.501812358377364,
 58.31850647152273,
 60.18446433840743,
 68.81291678436531,
 57.44404172709187,
 65.81627165065053,
 91.1692013198302,
 137.193727810169,
 158.71105930607527,
 138.80830525270818,
 150.59651932863005,
 259.93366049556516,
 165.3167354166484,
 125.19692993778129,
 6.7406847228795,
 75.49774022624453,
 71.31590900515224,
 62.720697418065605,
 66.22603835669743,
 62.876022160850745,
 79.46325871932831,
 77.08658031579995,
 87.704518118213,
 106.463496762147,
 25.455181182075076,
 34.52377637734999,
 29.56257429914216,
 15.863104300619382,
 9.557760333709366,
 8.975709582345813,
 9.730012913074727,
 10.067114000559174,
 10.630915277799053,
 10.359030790035339,
 10.690807553479813,
 9.409723402958244,
 13.186142137507641,
 21.977940386284086,
 22.68647875581447,
 19.249115053743854,
 19.99135240073815,
 19.953405137623342,
 21.00691328071047,
 21.001038249933703,
 22.962718910633527,
 23.989954440113948,
 26.053812358641164,
 26.196304447994223,
 27.324227145616785,
 29.19405298024,
 35.260398205916275,
 31.52109692394896,
 40.15686157527904,
 37.08924157446149,
 44.19230429769493,
 42.95231758674714,
 62.128284032177746,
 87.05789138594587,
 90.69257999879207,
 96.90959639432612,
 118.0596604903115,
 130.00657802697046,
 156.7280756741727,
 249.94882356352474,
 262.57550977480525,
 262.53698520207905,
 229.77521214469436,
 250.58123921873022,
 24.631190779672874,
 33.8909468405502,
 264.12461587719105,
 298.01335460760254,
 274.8205703080609,
 5.768500831492151,
 5.3648656682677505,
 5.535030397492241,
 5.777984994185368,
 3.920391165283632,
 3.835474844080279,
 4.0633879975767275,
 3.3442719173843933,
 3.504463896833947,
 4.110747700621122,
 4.174850345014175,
 4.263797501086712,
 4.389709410298581,
 5.948662705041971,
 8.363020518347719,
 9.11644904448465,
 9.836081040771349,
 10.55248823859155,
 10.54083790375901,
 10.270013715062637,
 9.882973667353378,
 11.169041412406587,
 11.026593832777218,
 12.426883505463111,
 12.749515109995235,
 12.680069497344347,
 13.470580557713594,
 12.998564314889075,
 17.90000386066896,
 16.49541542080515,
 19.756775158553893,
 20.51524439460403,
 21.569406386316658,
 21.51948139538681,
 32.20174769917446,
 73.185016016703,
 63.03383428913334,
 71.41994499962207,
 66.55256004825267,
 100.39504664439283,
 94.63744873068225,
 187.35768453344306,
 181.74800428805597,
 195.5671381126501,
 153.30511881673982,
 159.01760944052762,
 161.62699212224325,
 219.71723833967914,
 235.52549630619478,
 216.89730953945863,
 197.67948267944936,
 2.569362501630497,
 2.8441103794551372,
 2.22881870854846,
 2.2720903906988466,
 2.3866234521146854,
 2.4117433698589137,
 2.4588193456536627,
 2.399945563576182,
 2.403052858429185,
 2.3753559766640198,
 4.129343903932709,
 5.369634381559829,
 6.2301367762480275,
 6.656971077082388,
 6.5299162877661505,
 6.827549646731591,
 6.898929464958216,
 6.50089222856143,
 7.013347036147258,
 7.606545520764845,
 8.455448381949283,
 8.745245707030204,
 8.730763901951716,
 9.523606861776948,
 11.443339239737389,
 11.388437988963275,
 13.694383293577873,
 15.069144488789487,
 14.809912446557245,
 14.743343702766987,
 20.91056484214072,
 47.20203220990939,
 44.993150052084076,
 36.05746678634861,
 41.25397827139214,
 56.02473189505257,
 62.383837979584065,
 161.22278044570686,
 157.1695573059751,
 218.54661194595866,
 135.9311222861159,
 124.93458970006833,
 127.02862221262288,
 190.40513344845695,
 189.55847015106457,
 172.97136993143508,
 214.0154299736478]

In [19]:
data['Time Constant'] = Time

In [20]:
data.head()

   Relay Height  Amplitude  Time Period  Time Constant
0           6.0     0.0655       2.5988      48.241712
1           6.0     0.0830       2.7200      39.844859
2           6.0     0.0960       2.8004      35.466772
3           6.0     0.0840       2.8240      40.875800
4           6.0     0.0625       2.8216      54.891868

In [21]:
T = data['Time Constant'].tolist()

In [22]:
Delay = []
for i in range(len(A)):
    
    wcr = (2*3.1415)/(Ti[i]*3)
    a = (4*H[i])/((3.1415)*A[i])
    b = a**2 - 1
    arr = [b**0.5]
    d = np.arctan(arr)
    Delay.append((3.1415 - d[0])/wcr)

In [23]:
Delay

[1.9596814822124855,
 2.0540501110079643,
 2.117040897189494,
 2.1327638316782056,
 2.127159583967408,
 2.1160914350536797,
 2.1105832839694454,
 2.1148409323080166,
 2.1043964903457706,
 2.127993356625071,
 2.444724256560015,
 2.780417798313402,
 3.011482464539954,
 3.1716477461753487,
 3.3330572093427167,
 3.1965577554053777,
 3.3245297904366002,
 3.3263159098698556,
 3.4743001069195083,
 3.6020257787589465,
 3.7116496173078724,
 3.7849219823813853,
 3.878496666551372,
 3.9249216610691233,
 3.9338943422238675,
 4.570694896686821,
 4.709143373255675,
 4.840848313249562,
 5.144791855433478,
 5.473027352364397,
 5.62594569413338,
 6.644165385572104,
 7.244142143326253,
 7.933636915714798,
 9.243548018905168,
 9.697648332762025,
 9.020396440870028,
 8.212167186081983,
 4.500591967215301,
 2.1248583005772446,
 2.197248065641553,
 2.652519290730106,
 2.137529926961192,
 2.723284217851551,
 2.338606687239747,
 2.7848005705758787,
 2.819130710674887,
 2.9070984082447606,
 3.4626419479255484,
 2.040573616913786,
 2.042205527152439,
 1.971288480453035,
 1.2859250942597986,
 0.9340694989159568,
 0.9347868469401203,
 0.9532142701008106,
 0.9981949915078219,
 1.0288507211569584,
 1.019757545562866,
 1.067656795125609,
 1.0203029620546231,
 1.398388597147808,
 1.9393776437099428,
 2.0664101009568157,
 2.009303148211258,
 2.1486343185866574,
 2.206343171303506,
 2.2227806710847724,
 2.2721559704657155,
 2.4734589903078383,
 2.646967107892833,
 2.7940133266432476,
 2.846722937837954,
 2.9497710033407283,
 2.9918491671587977,
 3.8905081914703508,
 4.15586728869565,
 4.325548323457702,
 4.534891887012416,
 4.707625502947559,
 4.872315220561878,
 5.924237101256114,
 6.2213503224079405,
 7.208985505462821,
 7.886418599905349,
 8.381131808278964,
 9.16795135938795,
 9.355228218368799,
 13.452021776931975,
 14.254830556045723,
 14.375988468581017,
 14.580066847207847,
 15.723420899095833,
 1.6151128833034505,
 1.8160270201435185,
 15.393384529178116,
 15.689173686192671,
 14.855094674577385,
 0.6685725227009266,
 0.675349589699307,
 0.7109026439506927,
 0.7138404815551089,
 0.511619331954476,
 0.5307092398679085,
 0.5474240231352974,
 0.4733298089281435,
 0.4883056973598325,
 0.5814362768122101,
 0.5744610560846273,
 0.5899756412807421,
 0.5897018883750312,
 0.8505462296573574,
 1.1122362452268995,
 1.2666835314460707,
 1.372341593671913,
 1.4560795158232283,
 1.5071404080235764,
 1.5198019036306623,
 1.5215699172297208,
 1.678661196471072,
 1.759362195569491,
 1.8964522666971135,
 1.9432306033813704,
 1.9938017039660085,
 2.02197760094684,
 2.0614497852648537,
 2.6351352499520826,
 2.746761905099664,
 2.9693624189832777,
 3.1387188982400382,
 3.275049094274999,
 3.5458803476576928,
 4.517575651138605,
 5.485489845721474,
 6.384870566614892,
 6.92213396084546,
 7.171964599553188,
 8.303010467311859,
 8.669460949722772,
 11.50069039287101,
 12.285635595441843,
 12.556706063469232,
 13.056073766040203,
 14.114905613587576,
 14.714218648875713,
 16.676086542632575,
 17.5645753710449,
 17.9381422852149,
 15.900056614480459,
 0.4061686529240429,
 0.4336375861612858,
 0.3513895533853092,
 0.3724802226971445,
 0.3851045451076014,
 0.4000398672829107,
 0.41102073360649366,
 0.42055573049807954,
 0.4234312499834094,
 0.4250825732896647,
 0.6125363901344649,
 0.7672398327246719,
 0.9071714445184387,
 1.0131318836179148,
 1.1221167697319918,
 1.1589322338549684,
 1.2078223731653353,
 1.2160219829897356,
 1.3209790178095453,
 1.4277739602622364,
 1.5049394031991195,
 1.5593483881853027,
 1.601997061621471,
 1.6334838432039807,
 2.116412563311574,
 2.2171473349118496,
 2.37761045564881,
 2.543297399508555,
 2.662295819211669,
 2.8750856289127387,
 3.671034533040109,
 4.631686367277738,
 5.21473164576142,
 5.597732932541954,
 5.954082310063135,
 6.966231161789256,
 7.250172765323019,
 10.736176845313228,
 11.55296824535465,
 11.881666476208403,
 12.306178694698556,
 13.368253340347202,
 14.036070496450247,
 15.43498261987071,
 16.382866003924654,
 16.835846285322003,
 17.585074653876863]

In [24]:

data['Delay'] = Delay

In [25]:
data

     Relay Height  Amplitude  Time Period  Time Constant      Delay
0             6.0     0.0655       2.5988      48.241712   1.959681
1             6.0     0.0830       2.7200      39.844859   2.054050
2             6.0     0.0960       2.8004      35.466772   2.117041
3             6.0     0.0840       2.8240      40.875800   2.132764
4             6.0     0.0625       2.8216      54.891868   2.127160
..            ...        ...          ...            ...        ...
191          12.0     0.3530      18.4440     127.028622  14.036070
192          12.0     0.2600      20.3600     190.405133  15.434983
193          12.0     0.2770      21.5952     189.558470  16.382866
194          12.0     0.3115      22.1608     172.971370  16.835846
195          12.0     0.2635      23.1928     214.015430  17.585075

[196 rows x 5 columns]

In [26]:
data.to_csv('finaldata6.csv')